; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:lolin32_lite]
platform = espressif32
board = lolin32_lite
framework = arduino
upload_protocol = esptool
monitor_speed = 115200
lib_deps = 
    h2zero/NimBLE-Arduino@^2.3.7

[env:native]
platform = native
build_flags =
    -DNATIVE_TEST
    -Isrc
    --coverage
    -lgcov
test_build_src = true
lib_deps =
    Unity
# Ignore the embedded diagnostics test in the native environment, as it requires Arduino.h
test_ignore = test_embedded_diagnostics

[env:test_embedded]
platform = espressif32
board = lolin32_lite
framework = arduino
upload_protocol = esptool
monitor_speed = 115200
test_speed = 115200
; This tells PIO to upload the test code to the board
test_build_src = true
build_flags =
    -D EMBEDDED_TEST
lib_deps =
    h2zero/NimBLE-Arduino@^2.3.7
